import { ArrowLeft, ArrowUpRight, CalendarDays, Check, Heart, MapPin, MessageCircle, Quote, Sparkles } from "lucide-react";
import { Link } from "wouter";

const WHATSAPP = "5562995111648";
const stories = [
  { year: "2024", month: "Novembro", name: "Fernanda & Lucas", title: "O primeiro endereço da nossa família", place: "Residencial Anápolis · Senador Canedo", quote: "A WFC entendeu o que a gente precisava e explicou cada etapa do financiamento. Quando pegamos as chaves, parecia que todo o caminho tinha valido a pena.", image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1100&q=85", accent: "rose" },
  { year: "2024", month: "Agosto", name: "Dona Célia", title: "Um quintal para viver com os netos", place: "Jardim das Oliveiras · Senador Canedo", quote: "Eu queria uma casa térrea, com espaço e perto da minha filha. A Marina teve paciência para me mostrar tudo e encontramos exatamente o que eu imaginava.", image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1100&q=85", accent: "sand" },
  { year: "2023", month: "Março", name: "Rafael & Júlia", title: "Do plano no papel ao nosso lote", place: "Jardim Boa Vista · Senador Canedo", quote: "A gente ainda não estava pronto para comprar uma casa, mas queria começar. O lote foi a escolha certa e hoje já estamos construindo o nosso projeto.", image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1100&q=85", accent: "wine" },
  { year: "2022", month: "Outubro", name: "Família Oliveira", title: "Fim de semana com gosto de férias", place: "Recanto Verde · Bela Vista de Goiás", quote: "A chácara virou o lugar de encontro da família. Foi uma compra importante e nos sentimos seguros do primeiro contato até a documentação.", image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1100&q=85", accent: "green" },
];

export default function Clients() {
  return <div className="clients-page">
    <header className="clients-header"><div className="container clients-nav"><Link href="/" className="catalog-back"><ArrowLeft size={17} /> Voltar para início</Link><Link href="/" className="catalog-logo"><img src="/manus-storage/logo-wfc_8d426acc.jpg" alt="WFC Imóveis" /></Link><a className="catalog-contact" href={`https://wa.me/${WHATSAPP}`} target="_blank" rel="noreferrer"><MessageCircle size={15} /> Falar com a WFC</a></div></header>
    <main><section className="clients-hero"><div className="hero-glow" /><div className="container clients-hero-grid"><div><p className="section-label">Nossos clientes</p><h1>Histórias que<br /><em>ganharam endereço.</em></h1><p>Por trás de cada imóvel existe uma vontade, um plano e um novo capítulo. Esta é a nossa linha do tempo de conquistas — feita por pessoas que confiaram na WFC.</p><a className="button button-primary" href="#historias">Conhecer histórias <ArrowUpRight size={17} /></a></div><div className="clients-hero-art"><div className="clients-photo-main"><img src={stories[0].image} alt="Família em sua nova casa" /></div><div className="clients-photo-note"><Heart size={16} fill="currentColor" /><span>Mais de <strong>300</strong><br />histórias acompanhadas</span></div><div className="clients-quote"><Quote size={21} /><p>“A casa certa muda<br />o jeito de viver.”</p></div></div></div></section>
      <section className="clients-proof"><div className="container clients-proof-inner"><div><strong>300+</strong><span>famílias atendidas</span></div><div><strong>12 anos</strong><span>construindo confiança</span></div><div><strong>Senador Canedo</strong><span>e região no nosso mapa</span></div><div><Sparkles size={22} /><span>Atendimento<br />que fica na memória</span></div></div></section>
      <section className="clients-timeline-section" id="historias"><div className="container"><div className="clients-section-head"><div><p className="section-label">Uma conquista de cada vez</p><h2>Gente real.<br /><em>Casas cheias de vida.</em></h2></div><p>Nem toda jornada começa do mesmo lugar. Mas todas ficam mais leves quando existe alguém para orientar.</p></div><div className="clients-timeline">{stories.map((story, index) => <article className={`story-card ${story.accent}`} key={story.name}><div className="story-marker"><span>{String(index + 1).padStart(2, "0")}</span></div><div className="story-date"><strong>{story.year}</strong><span>{story.month}</span></div><div className="story-image"><img src={story.image} alt={`Conquista de ${story.name}`} /><span><Check size={13} /> Chaves entregues</span></div><div className="story-content"><p className="story-client"><MapPin size={13} /> {story.place}</p><h3>{story.title}</h3><p className="story-quote">“{story.quote}”</p><div className="story-person"><div className="story-avatar">{story.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</div><div><strong>{story.name}</strong><span>Cliente WFC Imóveis</span></div></div></div></article>)}</div></div></section>
      <section className="clients-invite"><div className="container clients-invite-inner"><div className="invite-icon"><Heart size={24} fill="currentColor" /></div><div><p className="section-label">Sua história pode ser a próxima</p><h2>Vamos encontrar o lugar<br /><em>onde ela começa?</em></h2></div><a className="button button-light" href={`https://wa.me/${WHATSAPP}?text=${encodeURIComponent("Olá, quero começar a minha história com a WFC Imóveis.")}`} target="_blank" rel="noreferrer">Começar minha busca <ArrowUpRight size={17} /></a></div></section>
    </main><footer className="site-footer clients-footer"><div className="container footer-bottom"><span>© 2026 WFC Imóveis. CRECI 21496.</span><Link href="/catalogo">Ver imóveis disponíveis <ArrowUpRight size={13} /></Link></div></footer>
  </div>;
}
