<?php
?><!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>WFC Imóveis — Sistema</title>
<style>
:root{--wine:#5b1726;--wine-dark:#3b0e18;--sand:#f7f1eb;--ink:#241c1e;--muted:#74686b;--line:#eadfd9;--white:#fff}*{box-sizing:border-box}body{margin:0;background:var(--sand);color:var(--ink);font:15px/1.5 Arial,sans-serif}button,input{font:inherit}.shell{min-height:100vh;display:grid;place-items:center;padding:24px}.card{background:var(--white);border:1px solid var(--line);border-radius:18px;box-shadow:0 18px 50px #3b0e1814;width:min(440px,100%);padding:38px}.brand{color:var(--wine);font-size:28px;font-weight:700;letter-spacing:-.04em;margin:0}.eyebrow{text-transform:uppercase;color:#9d6874;font-size:11px;letter-spacing:.18em;font-weight:700;margin:0 0 10px}.subtitle{color:var(--muted);margin:8px 0 28px}.field{display:grid;gap:7px;margin:16px 0}.field label{font-size:13px;font-weight:700}.field input{width:100%;border:1px solid var(--line);border-radius:10px;padding:12px 13px;outline:0}.field input:focus{border-color:var(--wine);box-shadow:0 0 0 3px #5b17261a}.btn{border:0;border-radius:10px;padding:12px 16px;background:var(--wine);color:#fff;font-weight:700;cursor:pointer;width:100%;margin-top:10px}.btn:hover{background:var(--wine-dark)}.error{color:#a32942;background:#fff0f2;border-radius:8px;padding:10px 12px;margin:14px 0;font-size:13px}.hidden{display:none!important}.app{min-height:100vh;display:grid;grid-template-columns:240px 1fr}.side{background:var(--wine-dark);color:#fff;padding:28px 20px}.side .brand{color:#fff;font-size:24px}.nav{display:grid;gap:7px;margin-top:40px}.nav button{background:transparent;border:0;color:#eadfe1;text-align:left;border-radius:9px;padding:11px 12px;cursor:pointer}.nav button.active,.nav button:hover{background:#ffffff18;color:#fff}.main{padding:34px;max-width:1200px;width:100%}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:30px}.top h1{font-family:Georgia,serif;font-size:38px;margin:0;color:var(--wine-dark)}.logout{width:auto;margin:0;background:#fff;color:var(--wine);border:1px solid var(--line)}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.stat,.panel{background:#fff;border:1px solid var(--line);border-radius:14px;padding:20px}.stat small{color:var(--muted)}.stat strong{display:block;font-size:34px;color:var(--wine);margin-top:8px}.panel{margin-top:22px}.panel h2{margin:0 0 6px;color:var(--wine-dark);font-size:20px}.muted{color:var(--muted)}@media(max-width:700px){.app{display:block}.side{padding:20px}.nav{display:flex;overflow:auto;margin-top:18px}.main{padding:22px}.top{align-items:flex-start}.top h1{font-size:30px}.stats{grid-template-columns:1fr}}
</style>
</head>
<body>
<div id="login" class="shell"><section class="card"><p class="eyebrow">Área restrita</p><h1 class="brand">WFC Imóveis</h1><p class="subtitle">Acesse o sistema de cadastros da equipe.</p><div id="loginError" class="error hidden"></div><form id="loginForm"><div class="field"><label for="identity">Usuário ou e-mail</label><input id="identity" autocomplete="username" required></div><div class="field"><label for="password">Senha</label><input id="password" type="password" autocomplete="current-password" required></div><button class="btn" type="submit">Entrar</button></form></section></div>
<div id="app" class="app hidden"><aside class="side"><h1 class="brand">WFC</h1><p class="muted" style="color:#d7c1c6">Sistema administrativo</p><nav class="nav"><button class="active">Início</button><button onclick="alert('Módulo de imóveis será conectado na próxima etapa.')">Imóveis</button><button onclick="alert('Módulo de clientes será conectado na próxima etapa.')">Clientes</button><button onclick="alert('Módulo de usuários será conectado na próxima etapa.')">Usuários</button><button onclick="alert('Perfil será conectado na próxima etapa.')">Meu perfil</button></nav></aside><main class="main"><header class="top"><div><p class="eyebrow">Painel interno</p><h1>Bom dia, <span id="userName">equipe</span>.</h1></div><button id="logout" class="btn logout">Sair</button></header><section class="stats"><article class="stat"><small>Imóveis cadastrados</small><strong id="properties">—</strong></article><article class="stat"><small>Clientes cadastrados</small><strong id="clients">—</strong></article><article class="stat"><small>Usuários da equipe</small><strong id="users">—</strong></article></section><section class="panel"><h2>Base segura conectada</h2><p id="status" class="muted">Carregando dados reais do MySQL…</p></section></main></div>
<script>
const api=(path,options={})=>fetch('api/v1/'+path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options}).then(async r=>{const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Não foi possível concluir a operação.');return b});
const login=document.getElementById('login'),app=document.getElementById('app'),error=document.getElementById('loginError');
function showApp(me){login.classList.add('hidden');app.classList.remove('hidden');document.getElementById('userName').textContent=me.user.name||me.user.username;loadSummary()}
async function loadSummary(){try{const b=await api('dashboard/summary');document.getElementById('properties').textContent=b.data.properties;document.getElementById('clients').textContent=b.data.clients;document.getElementById('users').textContent=b.data.users;document.getElementById('status').textContent='Sessão ativa. Os números acima foram consultados no banco de dados.'}catch(e){document.getElementById('status').textContent=e.message}}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();error.classList.add('hidden');const button=e.target.querySelector('button');button.disabled=true;button.textContent='Entrando…';try{showApp(await api('auth/login',{method:'POST',body:JSON.stringify({identity:document.getElementById('identity').value.trim(),password:document.getElementById('password').value})}))}catch(err){error.textContent=err.message;error.classList.remove('hidden')}finally{button.disabled=false;button.textContent='Entrar'}});
document.getElementById('logout').addEventListener('click',async()=>{await api('auth/logout',{method:'POST'}).catch(()=>{});app.classList.add('hidden');login.classList.remove('hidden')});
api('auth/me').then(showApp).catch(()=>{});
</script>
</body></html>
